name: cicd

on:
  push:
    branches:
      - main

jobs:
  cicd:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: docker build and run
      run: |
       docker build -t 3iamlucifer12/cicdnode -f Dockerfile .
       docker run -d -it -p 9000:8000 3iamlucifer12/cicdnode
        

     
